const ignoreUrl = [
    /\/public/,
    /\/login/,
    /\/dingLogin/,
    /\/attachs/,
    /\/chapters.*$/,
    /\/ps.*$/,
    /\/api.*$/,
    /\/swiper\/getListByPage/,
    /\/getListByPage/,
    /\/getByTypeCode/,
    /\/getUserInfo/,
    /\/getBeforeNext/,
    /\/courses\/getDataById/,
    /\/roleColumn\/getColumnByRoleId/,
    /\/user\/updateUserById/,
    /\/leave_msg\/create/,
    /\/comment.*$/,
    /\/courseType.*$/,
    /\/course.*$/,
    /\/homeColumns.*$/,
    /\/msgPush.*$/,
    /\/user.*$/,
    /\/examPaper\/getDataById$/,
    /\/exam\/getQuestionList$/
];
module.exports = ignoreUrl
