const ignoreUrl = [
    /\/public/,
    /\/login/,
    /\/dingLogin/,
    // /\/attachs/,
    // /\/chapters.*$/,
    // /\/ps.*$/,
    /\/api.*$/,
    // /\/blockToken.*$/,
    // /\/swiper\/getListByPage/,
    // /\/teacher_style\/getListByPage/,
    // /\/links\/getListByPage/,
    // /\/training\/getListByPage/,
    // /\/ps_menus\/getListByPage/,
    // /\/image_set\/getListByPage/,
    // /\/message\/getListByPage/,
    // /\/regulations\/getListByPage/,
    // /\/getListByPage/,
    // /\/getByTypeCode/,
    // /\/getUserInfo/,
    // /\/getBeforeNext/,
    // /\/lecturer\/getLecturerByPage/,
    /\/staffCompulsoryCourses\/getCourseByStaffId/, // /staffCompulsoryCourses/getCourseByStaffId
    // /\/courses\/getDataById/,
    // /\/api\/rest\/courses\/getListByPage/,
    // /\/courseType\/getListByPage/,
    /\/courses\/getDataListByStaffNum/,
    // /\/roleColumn\/getColumnByRoleId/,
    // /\/user\/updateUserById/,
    // /\/leave_msg\/create/,
    // /\/comment.*$/,
    // /\/courseType.*$/,
    // /\/course.*$/,
    /\/homeColumns.*$/,
    // /\/msgPush.*$/,
    // /\/user.*$/,
    // /\/examPaper\/getDataById$/,
    // /\/exam\/getQuestionList$/
];
module.exports = ignoreUrl
